Repository Workable/orka, pull requests merged in 2019-11, with the labels that each got.

#112 0.17.8
  package-lock.json
  package.json
Labels: production_release

#108 Use app.env in newrelic and honeybadger
  README.md
  src/builder.ts
  src/initializers/diamorphosis.ts
  src/initializers/honeybadger.ts
  src/initializers/newrelic/index.ts
  src/orka-builder.ts
  test/diamorphosis/diamorphosis.test.ts
Labels: feature

#114 Bump sinek to 8.1.0 (uses node-rdkafka 2.7.4) + bump minors
  package-lock.json
  package.json
Labels: chore

#116 Teach orka redis
  .vscode/settings.json
  README.md
  examples/redis-example/app.js
  examples/redis-example/config.js
  examples/redis-example/routes.js
  package-lock.json
  package.json
  src/index.ts
  src/initializers/redis.ts
  src/orka-builder.ts
  src/orka.ts
  test/env.ts
  test/initializers/mongodb.test.ts
  test/initializers/redis.test.ts
  test/orka-builder.test.ts
  test/orka.test.ts
  test/tsconfig.json
Labels: feature

#117 Redis will handle empty tls configuration
  README.md
  examples/redis-example/config.js
  package-lock.json
  package.json
  src/initializers/redis.ts
  test/initializers/redis.test.ts
Labels: hotfix

#118 Update README.md
  README.md
Labels: chore

#119 Null check of redis.options in redis initialization
  src/initializers/redis.ts
  test/initializers/redis.test.ts
Labels: feature

#120 Require redis after newrelic
  src/initializers/redis.ts
Labels: feature
