Repository Workable/orka, pull requests merged in 2019-07, with the labels that each got.

#38 Fix riviere, add codependency, make new relic optional
  package-lock.json
  package.json
  src/initializers/koa/riviere.ts
  src/initializers/newrelic/index.ts
  src/require-peer.ts
Labels: enhancement

#40 kafka improvements, sinek is optional
  examples/kafka-example/config.js
  examples/kafka-example/routes.js
  package-lock.json
  package.json
  src/builder.ts
  src/default-options.ts
  src/index.ts
  src/initializers/kafka/auth-options.ts
  src/initializers/kafka/base-kafka-handler.ts
  src/initializers/kafka/index.ts
  src/initializers/kafka/kafka.ts
  src/initializers/newrelic/index.ts
  src/orka.ts
  src/require-injected.ts
  src/typings/kafka.d.ts
  test/initializers/kafka/base-kafka-handler.test.ts
  test/initializers/kafka/kafka.test.ts
Labels: enhancement

#39 Add rabbitmq
  README.md
  examples/rabbitmq-example/app.js
  examples/rabbitmq-example/base-handler.js
  examples/rabbitmq-example/config.js
  examples/rabbitmq-example/example-handler.js
  examples/rabbitmq-example/routes.js
  package-lock.json
  package.json
  src/builder.ts
  src/index.ts
  src/initializers/rabbitmq/index.ts
  src/orka.ts
  test/initializers/kafka/auth-options.test.ts
  test/initializers/kafka/base-kafka-handler.test.ts
  test/initializers/kafka/kafka.test.ts
  test/initializers/log4js/honeybadger-appender.test.ts
  test/initializers/rabbitmq/index.test.ts
Labels: enhancement

#42 kafka optional config
  package-lock.json
  package.json
  src/initializers/kafka/index.ts
  test/initializers/kafka/index.test.ts
Labels: bug

#43 Improve rabbit tests
  package-lock.json
  test/initializers/rabbitmq/index.test.ts
  test/mocha.opts
Labels: feature

#47 use manual batching, add typings
  examples/kafka-example/config.js
  examples/kafka-example/routes.js
  package-lock.json
  package.json
  src/builder.ts
  src/initializers/kafka/base-kafka-handler.ts
  src/initializers/kafka/index.ts
  src/initializers/kafka/kafka.ts
  src/initializers/rabbitmq/index.ts
  src/typings/kafka.d.ts
  test/initializers/kafka/index.test.ts
Labels: enhancement

#53 0.9.1-beta.2
  package-lock.json
  package.json
  src/initializers/kafka/index.ts
  src/require-injected.ts
Labels: feature

#54 support sasl
  examples/kafka-example/config.js
  src/initializers/kafka/auth-options.ts
  src/initializers/kafka/kafka.ts
  src/typings/kafka.d.ts
  test/initializers/kafka/auth-options.test.ts
Labels: enhancement

#55 Custom error handler
  examples/custom-error-handler-example/app.js
  package-lock.json
  package.json
  src/builder.ts
  src/default-options.ts
  src/initializers/koa/error-handler.ts
  src/initializers/log4js/honeybadger-appender.ts
  test/env.ts
  test/initializers/koa/error-handler.test.ts
  test/mocha.opts
Labels: feature
