Repository Workable/orka, pull requests merged in 2019-05, with the labels that each got.

#2 Import honeybadger_appender to resolve vulnerabilities
  package-lock.json
  package.json
  src/initializers/diamorphosis.ts
  src/initializers/honeybadger.ts
  src/initializers/koa/index.ts
  src/initializers/log4js/honeybadger-appender.ts
  src/initializers/log4js/index.ts
  src/initializers/newrelic/index.ts
  src/orka.ts
  test/initializers/log4js/honeybadger-appender-test.ts
  test/orka.test.ts
Labels: feature

#9 Teach orka to stop server
  examples/simple-example/app.js
  src/builder.ts
  src/initializers/koa/index.ts
Labels: feature

#13 Teach orka to print logo
  examples/builder-example/app.js
  examples/builder-example/config.js
  examples/builder-example/routes.js
  examples/simple-example/app.js
  examples/simple-example/logo.txt
  src/builder.ts
  src/default-options.ts
  src/initializers/diamorphosis.ts
  src/initializers/logo.ts
  src/orka.ts
Labels: feature

#15 Add logo in readme
  README.md
  examples/simple-example/logo.txt
Labels: feature

#19 Convert builder to class
  src/builder.ts
Labels: enhancement

#20 0.2.0
  package-lock.json
  package.json
Labels: production_release

#21 refactoring and order of execution
  package-lock.json
  package.json
  src/builder.ts
  src/orka.ts
Labels: bug, enhancement
