Repository Workable/orka, pull requests merged in 2019-08, with the labels that each got.

#61 Bump rabbit and export it.
  package-lock.json
  package.json
  src/index.ts
Labels: feature

#63 Expose producer send arguments
  src/initializers/kafka/index.ts
  src/initializers/kafka/kafka.ts
Labels: enhancement

#67 [oneflow] v0.11.0
  package-lock.json
  package.json
Labels: production_release

#71 Refactoring: Call newrelic by default first. Log an error if config was already used. Log an error if newrelic is used before initialized
  examples/builder-example/app.js
  examples/simple-example/app.js
  examples/simple-example/routes.js
  src/builder.ts
  src/initializers/diamorphosis.ts
  src/initializers/newrelic/index.ts
  src/orka-builder.ts
  src/orka.ts
  src/tsconfig.json
  test/examples/examples.test.ts
  tslint.json
Labels: feature

#73 Fix newrelic initialization
  examples/builder-example/app.js
  examples/simple-example/app.js
  src/builder.ts
  src/initializers/newrelic/index.ts
  test/examples/examples.test.ts
Labels: feature

#74 Removes modules from index.ts
  src/builder.ts
  src/default-options.ts
  src/index.ts
  src/initializers/rabbitmq/index.ts
Labels: feature
