Repository Workable/orka, pull requests merged in 2019-10, with the labels that each got.

#90 Introduce omit keys for errorHandler
  examples/custom-error-handler-example/app.js
  package-lock.json
  src/default-options.ts
  src/initializers/koa/error-handler.ts
  test/initializers/koa/error-handler.test.ts
Labels: feature

#92 Fix exported types
  src/default-options.ts
  src/typings/orka.d.ts
  src/typings/orka.ts
Labels: feature

#93 Update use, beforeMiddleware, afterMiddleware types
  src/default-options.ts
  src/orka-builder.ts
Labels: feature

#95 Pass the ability to handle any http error logs to custom errorHandler
  src/default-options.ts
  src/initializers/koa/error-handler.ts
  test/initializers/koa/error-handler.test.ts
Labels: feature

#96 Update readme
  README.md
Labels: feature

#98 Fixes timeouts in MongoDB
  src/initializers/mongodb.ts
Labels: bug

#99 Revert mongo options order
  src/initializers/mongodb.ts
Labels: feature

#102 Bump rabbit-queue to 4.2.1
  package-lock.json
  package.json
Labels: hotfix

#104 Bump mongoose to 5.7.6
  package-lock.json
  package.json
Labels: feature
