Repository Workable/orka, pull requests merged in 2020-07, with the labels that each got.

#158 Fixes rabbit-queue logs
  src/initializers/rabbitmq/index.ts
Labels: feature

#160 Release of v0.31.0
  package-lock.json
  package.json
Labels: production_release

#161 Await next on health middleware
  src/middlewares/health.ts
  test/middlewares/health.test.ts
Labels: bug

#162 0.31.1
  package-lock.json
  package.json
Labels: production_release

#163 Add v before version on health endpoint
  src/middlewares/health.ts
  test/middlewares/health.test.ts
Labels: bug

#164 0.31.2
  package-lock.json
  package.json
Labels: production_release

#167 Fixes mongoose initialization before orka
  src/middlewares/health.ts
  test/examples/examples.test.ts
  test/initializers/clouddebugger.test.ts
Labels: feature

#166 Allow orka users not to use visitor middleware on defaults
  README.md
  src/orka-builder.ts
Labels: enhancement

#169 0.31.5
  package-lock.json
  package.json
  test/initializers/clouddebugger.test.ts
Labels: production_release

#168 Fixes clouddebugger test
  .npmignore
  test/initializers/clouddebugger.test.ts
Labels: feature

#170 0.31.6
  package-lock.json
  package.json
Labels: production_release

#173 Send error name to honeybadger
  src/initializers/log4js/honeybadger-appender.ts
  test/initializers/log4js/honeybadger-appender.test.ts
Labels: feature

#174 Better error logs for redis
  src/initializers/redis.ts
Labels: feature
