Repository Workable/orka, pull requests merged in 2020-12, with the labels that each got.

#207 [ENG-40] Mitigates statSync error for typescript apps
  package-lock.json
  package.json
  src/middlewares/health.ts
Labels: bug

#212 Extend prometheus class to support Histogram and Summary metrics
  src/initializers/prometheus/prometheus.ts
  test/initializers/prometheus/prometheus.test.ts
Labels: feature

#213 Add github scripts for testing, releasing and publishing to npm
  .github/workflows/create-release.yml
  .github/workflows/npm-publish.yml
  .github/workflows/test.yml
  src/utils.ts
Labels: feature

#214 [ENG-41] Add default option to riviere to blacklist DD traces
  package-lock.json
  src/initializers/diamorphosis.ts
  src/initializers/koa/riviere.ts
Labels: enhancement

#215 Bump typescript and prettier to use import type to get prom-client typings
  .prettierrc.json
  package-lock.json
  package.json
  src/initializers/kafka/base-kafka-handler.ts
  src/initializers/prometheus/prometheus.ts
  src/tsconfig.json
  src/typings/prometheus.d.ts
  test/middlewares/metrics.test.ts
Labels: feature

#216 Pass the whole config to DD tracer
  src/initializers/datadog/index.ts
Labels: chore
