Repository Workable/orka, pull requests merged in 2020-09, with the labels that each got.

#178 Resolve vulnerabilities by updating modules
  .mocharc.yaml
  package-lock.json
  package.json
  test/mocha.opts
Labels: feature

#180 Do not require ioredis if bull is not configured
  src/initializers/bull/index.ts
Labels: hotfix

#185 0.33.4 - Bump riviere to v1.9.0
  package-lock.json
  package.json
Labels: chore

#186 0.33.5
  examples/simple-example/config.js
  examples/simple-example/routes.js
  package-lock.json
  package.json
  src/initializers/koa/riviere.ts
Labels: hotfix
