Repository Workable/orka, pull requests merged in 2021-03, with the labels that each got.

#230 s/info/debug
  src/helpers/log-metrics.ts
  test/helpers/log-metrics.test.ts
Labels: feature

#232 [ENG-75] [PROD-1677] Add runWithContext to BaseKafkaHandler & BaseQueueHandler
  src/initializers/diamorphosis.ts
  src/initializers/kafka/base-kafka-handler.ts
  src/initializers/rabbitmq/index.ts
  test/initializers/kafka/base-kafka-handler.test.ts
  test/initializers/rabbitmq/index.test.ts
Labels: enhancement

#233 Update mongoose to fix vulnerability of mquery
  package-lock.json
  package.json
Labels: chore

#235 [PROD-1677][ENG-75] Automatically pass trace information on request headers
  package-lock.json
  package.json
  src/builder.ts
  src/initializers/riviere.ts
  src/orka-builder.ts
  test/initializers/prometheus/prometheus.test.ts
Labels: enhancement

#236 Rename default trace header name from x-request-id to x-orka-request-id
  README.md
  docs/configuration.md
  src/initializers/diamorphosis.ts
  test/examples/json-appender.test.ts
  test/examples/request-context-example.test.ts
  test/initializers/koa/error-handler.test.ts
Labels: chore

#238 Pass riviere outbound parameters to riviere
  src/initializers/diamorphosis.ts
  src/initializers/riviere.ts
Labels: chore
