Repository Workable/orka, pull requests merged in 2021-04, with the labels that each got.

#241 Add more docs for kafka
  docs/integrations/kafka.md
Labels: feature

#243 Improve docs for 'runWithContext'
  docs/integrations/kafka.md
  docs/integrations/rabbitmq.md
  docs/request-context.md
Labels: docs

#244 Last changes before releasing v2.0.0
  .github/workflows/test.yml
  README.md
  docs/index.md
  package-lock.json
  package.json
  src/builder.ts
  src/initializers/bull/bull.ts
  src/initializers/datadog/index.ts
  src/initializers/diamorphosis.ts
  src/initializers/honeybadger.ts
  src/initializers/kafka/kafka.ts
  src/orka-builder.ts
  test/examples/health-example.test.ts
  test/initializers/bull/bull.test.ts
Labels: feature

#245 Respect config default values for visitor, healthCheck
  src/initializers/diamorphosis.ts
  test/diamorphosis/config.js
  test/diamorphosis/diamorphosis.test.ts
Labels: hotfix

#250 Bump diamorphosis
  package-lock.json
  package.json
  src/initializers/kafka/index.ts
  test/initializers/kafka/index.test.ts
Labels: feature
