Repository Workable/orka, pull requests merged in 2021-06, with the labels that each got.

#257 Provide an easy way through config to controll wether to use ssl or not: (useSsl) by default true.
  __snapshots__/diamorphosis.test.ts.js
  docs/configuration.md
  docs/integrations/postgres.md
  package-lock.json
  package.json
  src/initializers/diamorphosis.ts
  src/initializers/postgres.ts
  test/diamorphosis/diamorphosis.test.ts
  test/initializers/postgres.test.ts
Labels: feature

#259 optionally check for already loaded dependencies prior to initialization
  src/builder.ts
Labels: bug

#260 [PROD-4557] Refactoring and addition of kafka batch handler
  docs/integrations/kafka.md
  src/initializers/kafka/base-kafka-handler.ts
  src/initializers/kafka/index.ts
  test/initializers/kafka/base-kafka-handler.test.ts
Labels: enhancement
